### ISSUE TITLE
Bypass permission

### ISSUE THREAD

**Issue by RaluGazdac** [Moshulika/mc.b-zone.ro#16]
Nu merge bypass la inventare in gm1. Nu pot deschide inventarele altor jucatori si nici chesturi sau barrel, etc. Si sa merg in gm 0 risc sa ma omoare in timp ce ii ajut. C”est ne pas possible.

**Comment by Moshulika** [comment]
Cum adica?

**Comment by Moshulika** [comment]
Aaaa, m-am prins, dar ai god pentru asta cu omoratul, oricum, vorbeste cu marius sa iti dea permisiune de bypass daca e ca el se ocupa cu paranoia
