### ISSUE TITLE
Comenzi

### ISSUE THREAD

**Issue by RaluGazdac** [Moshulika/mc.b-zone.ro#56]
Din cauza la autocomplete-ul adaugat inainte sa pleci pentru comenzi, desi scrii manual comanda, iti spune ca e comanda gresita, inexistenta si iti sugereaza o alta comanda.

**Comment by Moshulika** [comment]
Lasa aici niste exemple de comenzi care nu merg

**Comment by RaluGazdac** [comment]
/cr claim si cam tot ce tine de crate, /give
