### ISSUE TITLE
/dice 

### ISSUE THREAD

**Issue by irineaua** [Moshulika/mc.b-zone.ro#57]
cand dau /dice accept imi apare uneori asta:
![mc](https://user-images.githubusercontent.com/93745925/140435418-7fa5bc3b-8d96-4ecd-afe6-62c7c4da9215.png)

**Comment by Moshulika** [comment]
Zi-mi data si ora aprox. cand s-a intamplat

**Comment by irineaua** [comment]
05.11 pe la 1:30
