### ISSUE TITLE
Turf problem

### ISSUE THREAD

**Issue by Yanonne** [Moshulika/mc.b-zone.ro#58]
-Nu poți avea grinder protejat, daca folosești comanda /turfs claim mobii se vor opri din a se spawna, de asemenea nu poti folosi redstone in afara razei oferita de catre turf astfel neputand automatiza grind zone ul.
-Daca joci in duo chiar daca cealalta persoana iti ofera /turf allow tot nu vei putea folosi apa daca o parte este a ta iar una a lui, apa curgand doar intr-o zona oprindu-se inainte de a intra in alt chunk.
-Redstone nu poate fi folosit in afara protectiei, am enumerat si mai sus, tinand cont de preț este greu mai ales pentru un incepator sa cumpere o zona pentru fiecare ferma sau loc in care acesta doreste sa foloseasca redstone, din nou este imposibil de folosit daca joci in duo iar o parte din casa este deținuta de x iar restul de y.

**Comment by Moshulika** [comment]
Astea nu sunt probleme, asa au fost facute, cu chestiile astea in minte. Daca vrei mobi in protectie, ia spawner.
