### ISSUE TITLE
Bug de dispare itemu

### ISSUE THREAD

**Issue by Gsabie2** [Moshulika/mc.b-zone.ro#60]
Am fost la fish si din greseala am apasat f si mi am bagat elytra DE LA KIT in mana dreapta si s a dus
DORESC ELYTRA CU ENCHANTURILE DE LA KIT NU ELYTRA GOALA PRIMITA DE LA MAYHEM!

**Comment by Moshulika** [comment]
Ti se spune cand intrii la job sa nu intrii cu ceva in mana stanga.
