### ISSUE TITLE
/xp

### ISSUE THREAD

**Issue by RaluGazdac** [Moshulika/mc.b-zone.ro#65]
Nu merge sa trimiti xp, nici nu le porneste comanda.

**Comment by Moshulika** [comment]
![image](https://user-images.githubusercontent.com/30694786/147982514-1fa344d8-f7a4-40a4-8170-07a17c8701ee.png)

**Comment by Moshulika** [comment]
Nu este cu comanda, din meniul /xp apesi middle click pe sticluta si urmezi instructiunile

**Comment by RaluGazdac** [comment]
Mosh, nu le porneste replica aia sa bage numele, nu se intampla nimic cand apasa middle click, multi patesc asta
